In [24]:
%load_ext nb_black

<IPython.core.display.Javascript object>

# A jupyter notebook is a browser-based environment that integrates:
- A Kernel (python)
- Text
- Executable code
- Plots and images
- Rendered mathematical equations

## Cell

The basic unit of a jupyter notebook is a `cell`. A `cell` can contain any of the above elements. 

In a notebook, to run a cell of code, hit `Shift-Enter`. This executes the cell and puts the cursor in the next cell below, or makes a new one if you are at the end.  Alternately, you can use:
    
- `Alt-Enter` to force the creation of a new cell unconditionally (useful when inserting new content in the middle of an existing notebook).
- `Control-Enter` executes the cell and keeps the cursor in the same cell, useful for quick experimentation of snippets that you don't need to keep permanently.

## Hello World

In [11]:
print("Hello, bitch!")

Hello, bitch!


In [2]:
# lines that begin with a # are treated as comment lines and not executed

# print("This line is not printed")

print("This line is printed")

This line is printed


## Create a variable

In [3]:
my_variable = 3.0 * 2.0

## Print out the value of the variable

In [4]:
print(my_variable)

6.0


## or even easier:

In [5]:
my_variable

6.0

# Datatypes

In computer programming, a data type is a classification identifying one of various types that data
can have. 

The most common data type we will see in this class are:

* **Integers** (`int`): Integers are the classic cardinal numbers: ... -3, -2, -1, 0, 1, 2, 3, 4, ...

* **Floating Point** (`float`): Floating Point are numbers with a decimal point: 1.2, 34.98, -67,23354435, ...

* **Scientific Notation** - Floating point values can also be expressed in scientific notation: `1e3 = 1000`

* **Booleans** (`bool`): Booleans types can only have one of two values: `True` or `False`. In many languages 0 is considered `False`, and any other value is considered `True`.

* **Strings** (`str`): Strings can be composed of one or more characters: ’a’, ’spam’, ’spam spam eggs and spam’. Usually quotes (’) are used to specify a string. For example ’12’ would refer to the string, not the integer.

In [6]:
my_var_a = 1
my_var_b = 2.3
my_var_c = True
my_var_d = 'Spam'
my_var_e = '4.5'

In [7]:
type(my_var_a), type(my_var_b), type(my_var_c), type(my_var_d), type(my_var_e)

(int, float, bool, str, str)

In [8]:
my_var_a + my_var_b, type(my_var_a + my_var_b)

(3.3, float)

In [9]:
my_var_a + my_var_c, type(my_var_a + my_var_c)    # True = 1

(2, int)

In [10]:
my_var_b + my_var_e

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [12]:
str(my_var_b) + my_var_e

'2.34.5'

In [13]:
my_var_b + float(my_var_e)

6.8

# NumPy (Numerical Python) is the fundamental package for scientific computing with Python.

### Load the numpy library:

In [14]:
import numpy as np

#### pi and e are  built-in constants:

In [15]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

## Here is a link to all [Numpy math functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

----

# Arrays - Collections of datatypes

### Our basic array will be the NumPy array

* Each element of the array has a **Value**
* The *position* of each **Value** is called its **Index**

![Image of Index](./images/PosIndex_sm.png)

In [16]:
my_array = np.array([7, 4, 8, 5, 7, 3])

In [17]:
my_array

array([7, 4, 8, 5, 7, 3])

## Indexing

In [18]:
my_array[0]    # The Value at Index = 0

7

In [19]:
my_array[-1]    # The last Value in the array

3

![Image of Index](./images/NegIndex_sm.png)

## Slices

`x[start:stop:step]`
 
- `start` is the first Index that you want [default = first element]
- `stop`  is the first Index that you **do not** want [default = last element]
- `step`  defines size of `step` and whether you are moving forwards (positive) or backwards (negative) [default = 1]

In [20]:
my_array

array([7, 4, 8, 5, 7, 3])

In [21]:
my_array[0:4]           # first 4 items

array([7, 4, 8, 5])

In [22]:
my_array[:4]            # same

array([7, 4, 8, 5])

In [23]:
my_array[0:4:2]         # first four item, step = 2

array([7, 8])

In [25]:
my_array[3::-1]         # first four items backwards, step = -1

array([5, 8, 4, 7])

<IPython.core.display.Javascript object>

In [26]:
my_array[::-1]          # Reverse the array x

array([3, 7, 5, 8, 4, 7])

<IPython.core.display.Javascript object>

In [27]:
print(my_array[-3:])    # last 3 elements of the array x

[5 7 3]


<IPython.core.display.Javascript object>

## There are lots of different `methods` that can be applied to a NumPy array

In [28]:
my_array.size                   # Number of elements in x

6

<IPython.core.display.Javascript object>

In [29]:
my_array.mean()                 # Average of the elements in x

5.666666666666667

<IPython.core.display.Javascript object>

In [30]:
my_array.sum()                  # Total of the elements in x

34

<IPython.core.display.Javascript object>

In [31]:
my_array[-3:].sum()              # Total of last 3 elements in x

15

<IPython.core.display.Javascript object>

In [32]:
my_array.cumsum()                # Cumulative sum

array([ 7, 11, 19, 24, 31, 34])

<IPython.core.display.Javascript object>

In [33]:
my_array.cumsum()/my_array.sum()        # Cumulative percentage

array([0.20588235, 0.32352941, 0.55882353, 0.70588235, 0.91176471,
       1.        ])

<IPython.core.display.Javascript object>

In [34]:
my_array.

<IPython.core.display.Javascript object>

## Help about a `method`:

In [35]:
?my_array.min

<IPython.core.display.Javascript object>

Docstring:
a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)

Return the minimum along a given axis.

Refer to `numpy.amin` for full documentation.

See Also
--------
numpy.amin : equivalent function
Type:      builtin_function_or_method


## NumPy math works over an entire array:

In [36]:
my_array * 2

array([14,  8, 16, 10, 14,  6])

<IPython.core.display.Javascript object>

In [37]:
sin(my_array)     # need to Numpy's math functions

NameError: name 'sin' is not defined

<IPython.core.display.Javascript object>

In [38]:
np.sin(my_array)

array([ 0.6569866 , -0.7568025 ,  0.98935825, -0.95892427,  0.6569866 ,
        0.14112001])

<IPython.core.display.Javascript object>

## Masking - Filtering data

In [ ]:
mask1 = np.where(my_array > 5)
my_array, mask1

In [ ]:
my_array[mask1]

In [ ]:
mask2 = np.where((my_array>3) & (my_array<6))
my_array[mask2]

In [ ]:
mask3 = np.where(my_array >= 5)
my_array[mask3]

In [ ]:
# Set all values of x that match mask3 to 0

my_array[mask3] = 0
my_array

## Sorting

In [ ]:
my_array = np.array([7, 4, 8, 5, 7, 3])

In [ ]:
np.sort(my_array)

In [ ]:
np.sort(my_array)[::-1]

In [ ]:
np.sort(my_array)[0:3]

# Control Flow

Like all computer languages, Python supports the standard types of control flows including:

* IF statements
* FOR loops

In [ ]:
my_variable = -1

if my_variable > 0:

    print("This number is positive")

else:

    print("This number is NOT positive")

In [ ]:
my_variable = 0

if my_variable > 0:

    print("This number is positive")

elif my_variable == 0:

    print("This number is zero")

else:

    print("This number is negative")

## `For` loops are different in python.

You do not need to specify the beginning and end values of the loop

In [ ]:
my_array

In [ ]:
for value in my_array:
    print(value)

In [ ]:
for index,value in enumerate(my_array):
    print(index,value)

In [ ]:
for george,ringo in enumerate(my_array):
    print(george,ringo)

# Functions

In computer science, a `function` (also called a `procedure`, `method`, `subroutine`, or `routine`) is a portion
of code within a larger program that performs a specific task and is relatively independent of the
remaining code. The big advantage of a `function` is that it breaks a program into smaller, easier
to understand pieces. It also makes debugging easier. A `function` can also be reused in another
program.

The basic idea of a `function` is that it will take various values, do something with them, and `return` a result. The variables in a `function` are local. That means that they do not affect anything outside the `function`.

Below is an example of a `function` that solves the equation:

$ f(a,b,x) = b^{2}\cos(a^{2}\pi x)$

In the example the name of the `function` is **find_f** (you can name `functions` what ever you want). The `function` **find_f** takes three arguments `a`, `b` and `y`, and returns the value of the equation to the main program. In the main program a variable named `value_f` is assigned the value returned by **find_f**. Notice that in the main program the `function` **find_f** is called using the arguments `scalar_a`, `scalar_b` and `array_x`. Since the variables in the `function` are local, you do not have name them `a`, `b` and `x` in the main program.

In [ ]:
def find_f(my_a, my_b, my_x):

    result = my_b ** 2 * np.cos(my_a ** 2 * np.pi * my_x)   # assign the variable result the value of the function
    return result                                           # return the value of the function to the main program

`np.linspace` -  create a new array filled with evenly spaced numbers over a specified interval `(start, stop, num)`

In [ ]:
scalar_a = 7
scalar_b = 0.5
array_x = np.linspace(0, 2*np.pi, 20)

In [ ]:
scalar_a, scalar_b, array_x

In [ ]:
value_f = find_f(scalar_a, scalar_b, array_x)

value_f

### The results of one function can be used as the input to another function

$$ g(z) = \frac{z}{e^{z}}$$

In [ ]:
def find_g(my_z):

    result = my_z / np.exp(my_z)
    return result

In [ ]:
find_g(value_f)

In [ ]:
find_g(find_f(scalar_a, scalar_b, array_x))

# Creating Arrays

## Numpy has a wide variety of ways of creating arrays: [Array creation routines](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-creation.html)

In [ ]:
# a new array filled with zeros

array_0 = np.zeros(10)

array_0

In [ ]:
# a new array filled with ones

array_1 = np.ones(10)

array_1

In [ ]:
# a new array filled with evenly spaced values within a given interval

array_2 = np.arange(10,20)

array_2

In [ ]:
# a new array filled with evenly spaced numbers over a specified interval (start, stop, num)

array_3 = np.linspace(10,20,5)

array_3

In [ ]:
# a new array filled with evenly spaced numbers over a log scale. (start, stop, num, base)

array_4 = np.logspace(1,2,5,10)

array_4